In [1]:
import numpy as np
import pandas as pd

In [2]:
movie=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
movie.shape

(4803, 20)

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
#merging datasets
final=pd.merge(movie,credits,left_on='id',right_on='movie_id')[['id','original_title','genres','keywords','overview','cast','crew']]

In [9]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
final.isnull().sum()

id                0
original_title    0
genres            0
keywords          0
overview          3
cast              0
crew              0
dtype: int64

In [11]:
final.dropna(subset=['overview'],inplace=True)

In [12]:
final.isnull().sum()

id                0
original_title    0
genres            0
keywords          0
overview          0
cast              0
crew              0
dtype: int64

In [13]:
final['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
import ast
genres=[]
def convert(s):
    l1=[]
    for i in ast.literal_eval(s):
        l1.append(i['name'])
        if i['name'] not in genres:
            genres.append(i['name'])
    text=l1[:]
   
    l1=[]
    return text

In [15]:
final['genres']=final['genres'].apply(convert)

In [16]:
final['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [17]:
print(genres)

['Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Crime', 'Drama', 'Thriller', 'Animation', 'Family', 'Western', 'Comedy', 'Romance', 'Horror', 'Mystery', 'History', 'War', 'Music', 'Documentary', 'Foreign', 'TV Movie']

In [18]:
print(len(genres))

20

In [19]:
final['keywords']=final['keywords'].apply(convert)

In [20]:
final['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [21]:
final['overview']=final['overview'].apply(lambda x : x.split(' '))

In [22]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def fetch_cast(text):
    L=[]
    counter=0
    for i in ast.literal_eval(text):
            if counter<3:
                L.append(i['name'])
            else:
                break
            counter+=1
    L1=L[:]
    L.clear()
    return L1

In [24]:
final['cast']=final['cast'].apply(fetch_cast)

In [25]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def fetch_director(text):
    L=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director':
            L.append(i['name'])
            break
    L1=L[:]
    L.clear()
    return L1

In [27]:
final['crew']=final['crew'].apply(fetch_director)

In [28]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
final['tags']=final['genres']+final['keywords']+final['overview']+final['cast']+final['crew']

In [30]:
def remove_space(L):
    L1=[]
    for i in L:
        L1.append(i.replace(' ',''))
    
    L2=L1[:] 
    L1.clear()
    return L2

In [31]:
final['tags']=final['tags'].apply(remove_space)

In [32]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, ScienceFiction, basedonnov..."

In [33]:
final['tags']=final['tags'].apply(lambda x:" ".join(x))

In [34]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],Action Adventure ScienceFiction basedonnovel m...

In [35]:
final['tags']=final['tags'].apply(lambda x:x.lower())

In [36]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],action crime drama thriller dccomics crimefigh...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],action adventure sciencefiction basedonnovel m...

In [37]:
def convert(name):
    return name.lower()

final['lower_title']=final['original_title'].apply(convert)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv=CountVectorizer(stop_words='english',max_features=10000)

In [40]:
X = cv.fit_transform(final['tags']).toarray()

In [41]:
X.shape

(4800, 10000)

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity_matrix = cosine_similarity(X)

In [44]:
import pickle
pickle.dump(cv, open('cv.pkl','wb'))
pickle.dump(similarity_matrix, open('similarity_matrix.pkl','wb'))

In [45]:
similarity_matrix.shape

(4800, 4800)

In [46]:
# finding the index of the movie
final[final['original_title']=='Avengers: Age of Ultron'].index[0]

7

In [47]:
mov=np.array(final['lower_title'])

In [48]:
def recommend(movie_name):
    recs=[]
    movie_name=movie_name.lower()
    if movie_name in mov:
        movie_index=final[final['lower_title']== movie_name].index[0]

        L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])

        
        for i in L[1:6]:
            print(final.iloc[i[0]]['original_title'])
            recs.append(final.iloc[i[0]]['original_title'])
        return recs
    #if movie name not present in dataset
    else:
        return recs

In [49]:
recs=recommend('The Dark Kight rises')

In [50]:
print(recs)

[]

In [51]:
recs=recommend('Avengers: age of ultron')

Iron Man
The Avengers
Iron Man 3
Captain America: Civil War
Iron Man 2

In [52]:
recs=recommend('spectre')

Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love
Thunderball

In [53]:
recs=recommend('Minions')

Despicable Me 2
The Croods
The Master of Disguise
Penguins of Madagascar
Cars 2

In [54]:
recs=recommend('zyx')

In [55]:
final['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

In [56]:
def convert_cast(name):
    l1=[]
    for i in name:
        l1.append(i.lower())
    return l1

In [57]:
final['lower_cast']=final['cast'].apply(convert_cast)

In [58]:
final['lower_cast'].head()

0    [sam worthington, zoe saldana, sigourney weaver]
1       [johnny depp, orlando bloom, keira knightley]
2        [daniel craig, christoph waltz, léa seydoux]
3        [christian bale, michael caine, gary oldman]
4      [taylor kitsch, lynn collins, samantha morton]
Name: lower_cast, dtype: object

In [59]:
l1=[]
def listt(c):
    l1.append(c)
    return l1

listt_cast=[]
for i in range(10):
    final['cast']

In [60]:
listt_cast=final['lower_cast'].tolist()

In [61]:
hero='Daniel Craig'
#finding actor's one movie and recommending similar
def recommend(actor_name):
    recs=[]
    flag=0
    actor_name=actor_name.lower()
    for i in range(len(listt_cast)):
        if actor_name in listt_cast[i]:
            
          
            print("yep")
            flag=1
            title= final.iloc[i]['lower_title']
            
            movie_index=final[final['lower_title']== title].index[0]

            L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])


            for i in L[1:6]:
                print(final.iloc[i[0]]['original_title'])
                recs.append(final.iloc[i[0]]['original_title'])
            return recs
                
    #if actor name not present in dataset
    if flag==0:
            print("nah")

In [62]:
recommend(hero)

yep
Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love
Thunderball

['Quantum of Solace',
 'Never Say Never Again',
 'Skyfall',
 'From Russia with Love',
 'Thunderball']

In [63]:
#finding all movies of that actor
def recommend(actor_name):
    recs=[]
    flag=0
    actor_name=actor_name.lower()
    for i in range(len(listt_cast)):
        if actor_name in listt_cast[i]:
            
            flag=1
            title= final.iloc[i]['original_title']
            
            recs.append(title)
    return recs
                
    #if movie name not present in dataset
    if flag==0:
            return recs

In [64]:
hero='ben barnes'
x=recommend(hero)

In [65]:
def final_movs(x):
    if len(x)>5:
        return x[:5]
    else:
        return x

In [66]:
movies=final_movs(x)
print(movies)

['The Chronicles of Narnia: Prince Caspian', 'Seventh Son', 'Easy Virtue']

In [67]:
print(listt_cast)

[['sam worthington', 'zoe saldana', 'sigourney weaver'], ['johnny depp', 'orlando bloom', 'keira knightley'], ['daniel craig', 'christoph waltz', 'léa seydoux'], ['christian bale', 'michael caine', 'gary oldman'], ['taylor kitsch', 'lynn collins', 'samantha morton'], ['tobey maguire', 'kirsten dunst', 'james franco'], ['zachary levi', 'mandy moore', 'donna murphy'], ['robert downey jr.', 'chris hemsworth', 'mark ruffalo'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['ben affleck', 'henry cavill', 'gal gadot'], ['brandon routh', 'kevin spacey', 'kate bosworth'], ['daniel craig', 'olga kurylenko', 'mathieu amalric'], ['johnny depp', 'orlando bloom', 'keira knightley'], ['johnny depp', 'armie hammer', 'william fichtner'], ['henry cavill', 'amy adams', 'michael shannon'], ['ben barnes', 'william moseley', 'anna popplewell'], ['robert downey jr.', 'chris evans', 'mark ruffalo'], ['johnny depp', 'penélope cruz', 'ian mcshane'], ['will smith', 'tommy lee jones', 'josh brolin'], ['martin freeman', 'ian mckellen', 'richard armitage'], ['andrew garfield', 'emma stone', 'rhys ifans'], ['russell crowe', 'cate blanchett', 'max von sydow'], ['martin freeman', 'ian mckellen', 'richard armitage'], ['dakota blue richards', 'nicole kidman', 'daniel craig'], ['naomi watts', 'jack black', 'adrien brody'], ['kate winslet', 'leonardo dicaprio', 'frances fisher'], ['chris evans', 'robert downey jr.', 'scarlett johansson'], ['taylor kitsch', 'alexander skarsgård', 'rihanna'], ['chris pratt', 'bryce dallas howard', 'irrfan khan'], ['daniel craig', 'judi dench', 'javier bardem'], ['tobey maguire', 'kirsten dunst', 'james franco'], ['robert downey jr.', 'gwyneth paltrow', 'don cheadle'], ['mia wasikowska', 'johnny depp', 'anne hathaway'], ['hugh jackman', 'halle berry', 'ian mckellen'], ['billy crystal', 'john goodman', 'steve buscemi'], ['shia labeouf', 'megan fox', 'josh duhamel'], ['mark wahlberg', 'stanley tucci', 'kelsey grammer'], ['james franco', 'mila kunis', 'rachel weisz'], ['andrew garfield', 'emma stone', 'jamie foxx'], ['garrett hedlund', 'jeff bridges', 'olivia wilde'], ['owen wilson', 'larry the cable guy', 'michael caine'], ['ryan reynolds', 'blake lively', 'peter sarsgaard'], ['tom hanks', 'tim allen', 'ned beatty'], ['christian bale', 'sam worthington', 'anton yelchin'], ['vin diesel', 'paul walker', 'dwayne johnson'], ['brad pitt', 'mireille enos', 'abigail hargrove'], ['hugh jackman', 'james mcavoy', 'michael fassbender'], ['chris pine', 'zachary quinto', 'zoe saldana'], ['nicholas hoult', 'eleanor tomlinson', 'ewan mcgregor'], ['leonardo dicaprio', 'tobey maguire', 'carey mulligan'], ['jake gyllenhaal', 'gemma arterton', 'ben kingsley'], ['idris elba', 'charlie hunnam', 'charlie day'], ['shia labeouf', 'john malkovich', 'ken jeong'], ['harrison ford', 'cate blanchett', 'shia labeouf'], ['raymond ochoa', 'jack bright', 'jeffrey wright'], ['kelly macdonald', 'julie walters', 'billy connolly'], ['chris pine', 'zachary quinto', 'karl urban'], ['ben burtt', 'elissa knight', 'jeff garlin'], ['chris tucker', 'jackie chan', 'hiroyuki sanada'], ['john cusack', 'amanda peet', 'chiwetel ejiofor'], ['gary oldman', 'jim carrey', 'steve valentine'], ['mila kunis', 'channing tatum', 'sean bean'], ['alexander skarsgård', 'margot robbie', 'christoph waltz'], ['william moseley', 'anna popplewell', 'skandar keynes'], ['james mcavoy', 'michael fassbender', 'jennifer lawrence'], ['christian bale', 'heath ledger', 'aaron eckhart'], ['ed asner', 'christopher plummer', 'jordan nagai'], ['seth rogen', 'reese witherspoon', 'hugh laurie'], ['robert downey jr.', 'terrence howard', 'jeff bridges'], ['ben kingsley', 'sacha baron cohen', 'asa butterfield'], ['will smith', 'kevin kline', 'kenneth branagh'], ['brendan fraser', 'jet li', 'john hannah'], ['will smith', 'margot robbie', 'joel kinnaman'], ['steve carell', 'lauren graham', 'john goodman'], ['tom cruise', 'emily blunt', 'brendan gleeson'], ['kevin costner', 'chaim girafi', 'rick aviles'], ['dennis quaid', 'channing tatum', 'marlon wayans'], ['amy poehler', 'phyllis smith', 'richard kind'], ['neel sethi', 'bill murray', 'ben kingsley'], ['robert downey jr.', 'gwyneth paltrow', 'don cheadle'], ['kristen stewart', 'charlize theron', 'chris hemsworth'], ['angelina jolie', 'elle fanning', 'sharlto copley'], ['andy serkis', 'jason clarke', 'gary oldman'], ['josh hartnett', 'simone kessell', 'tamsin egerton'], ['keanu reeves', 'hiroyuki sanada', 'kou shibasaki'], ['chris evans', 'samuel l. jackson', 'scarlett johansson'], ['mike myers', 'eddie murphy', 'cameron diaz'], ['britt robertson', 'george clooney', 'raffey cassidy'], ['scott adsit', 'ryan potter', 'daniel henney'], ['john c. reilly', 'sarah silverman', 'jack mcbrayer'], ['tom hanks', 'michael jeter', 'nona gaye'], ['liam hemsworth', 'jeff goldblum', 'bill pullman'], ['jay baruchel', 'gerard butler', 'craig ferguson'], ['arnold schwarzenegger', 'nick stahl', 'claire danes'], ['chris pratt', 'zoe saldana', 'dave bautista'], ['matthew mcconaughey', 'jessica chastain', 'anne hathaway'], ['leonardo dicaprio', 'joseph gordon-levitt', 'ellen page'], ['hiroki hasegawa', 'yutaka takenouchi', 'satomi ishihara'], ['ian mckellen', 'martin freeman', 'richard armitage'], ['paul walker', 'vin diesel', 'michelle rodriguez'], ['cate blanchett', 'brad pitt', 'tilda swinton'], ['james mcavoy', 'michael fassbender', 'jennifer lawrence'], ['jennifer lawrence', 'josh hutcherson', 'liam hemsworth'], ['nicolas cage', 'jay baruchel', 'monica bellucci'], ['kurt russell', 'richard dreyfuss', 'josh lucas'], ['johnny depp', 'mia wasikowska', 'anne hathaway'], ['mike myers', 'eddie murphy', 'cameron diaz'], ['paula patton', 'travis fimmel', 'ben foster'], ['arnold schwarzenegger', 'jason clarke', 'emilia clarke'], ['skandar keynes', 'georgie henley', 'simon pegg'], ['ben affleck', 'josh hartnett', 'kate beckinsale'], ['shia labeouf', 'josh duhamel', 'megan fox'], ['colin farrell', 'angelina jolie', 'val kilmer'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['will smith', 'charlize theron', 'jason bateman'], ['will smith', 'alice braga', 'charlie tahan'], ['johnny depp', 'freddie highmore', 'david kelly'], ['patton oswalt', 'ian holm', 'lou romano'], ['christian bale', 'michael caine', 'liam neeson'], ['ben stiller', 'jada pinkett smith', 'david schwimmer'], ['ben stiller', 'amy adams', 'owen wilson'], ['hugh jackman', 'liev schreiber', 'danny huston'], ['keanu reeves', 'laurence fishburne', 'carrie-anne moss'], ['kristen bell', 'idina menzel', 'jonathan groff'], ['keanu reeves', 'carrie-anne moss', 'laurence fishburne'], ['chris hemsworth', 'natalie portman', 'tom hiddleston'], ['tom hardy', 'charlize theron', 'nicholas hoult'], ['tom hanks', 'ewan mcgregor', 'ayelet zurer'], ['chris hemsworth', 'natalie portman', 'tom hiddleston'], ['john travolta', 'miley cyrus', 'susie essman'], ['sam rockwell', 'penélope cruz', 'tracy morgan'], ['sam worthington', 'liam neeson', 'ralph fiennes'], ['johnny depp', 'michelle pfeiffer', 'helena bonham carter'], ['tom cruise', 'rebecca ferguson', 'simon pegg'], ['benicio del toro', 'anthony hopkins', 'emily blunt'], ['jerry seinfeld', 'renée zellweger', 'jim cummings'], ['jack black', 'angelina jolie', 'dustin hoffman'], ['noah ringer', 'nicola peltz', 'jackson rathbone'], ['tom cruise', 'philip seymour hoffman', 'ving rhames'], ['channing tatum', 'jamie foxx', 'joey king'], ['seth green', 'joan cusack', 'dan fogler'], ['hugh jackman', 'kate winslet', 'ian mckellen'], ['levi miller', 'garrett hedlund', 'hugh jackman'], ['ty burrell', 'max charles', 'ariel winter'], ['brad pitt', 'orlando bloom', 'eric bana'], ['ben stiller', 'sacha baron cohen', 'david schwimmer'], ['pierce brosnan', 'halle berry', 'rosamund pike'], ['melissa mccarthy', 'kristen wiig', 'kate mckinnon'], ['bruce willis', 'billy bob thornton', 'ben affleck'], ['tommy lee jones', 'will smith', 'rip torn'], ['ray winstone', 'angelina jolie', 'anthony hopkins'], ['jack black', 'bryan cranston', 'dustin hoffman'], ['tom cruise', 'jeremy renner', 'simon pegg'], ['chris pine', 'alec baldwin', 'jude law'], ['jim carrey', 'téa leoni', 'alec baldwin'], ['tom cruise', 'ken watanabe', 'william atherton'], ['christian bale', 'joel edgerton', 'john turturro'], ['chris pine', 'zachary quinto', 'leonard nimoy'], ['tobey maguire', 'willem dafoe', 'kirsten dunst'], ['jay baruchel', 'gerard butler', 'kristen wiig'], ['brenton thwaites', 'nikolaj coster-waldau', 'gerard butler'], ['josh lucas', 'jessica biel', 'jamie foxx'], ['malin åkerman', 'billy crudup', 'carla gugino'], ['mel gibson', 'danny glover', 'joe pesci'], ['eric bana', 'jennifer connelly', 'sam elliott'], ['dwayne johnson', 'd.j. cotrona', 'adrianne palicki'], ['matthew mcconaughey', 'penélope cruz', 'steve zahn'], ['donald sutherland', 'ming-na wen', 'alec baldwin'], ['chris evans', 'hugo weaving', 'tommy lee jones'], ['pierce brosnan', 'sophie marceau', 'robert carlyle'], ['russell crowe', 'paul bettany', "james d'arcy"], ['kristen stewart', 'robert pattinson', 'taylor lautner'], ['elijah wood', 'robin williams', 'pink'], ['edward norton', 'liv tyler', 'tim roth'], ['ruby barnhill', 'mark rylance', 'rebecca hall'], ['leonardo dicaprio', 'tom hardy', 'will poulter'], ['ryan reynolds', 'paul giamatti', 'michael peña'], ['johnny depp', 'isla fisher', 'ned beatty'], ['tom mcgrath', 'chris miller', 'christopher knights'], ['matt damon', 'julia stiles', 'david strathairn'], ['jack black', 'dustin hoffman', 'angelina jolie'], ['paul rudd', 'michael douglas', 'evangeline lilly'], ['jennifer lawrence', 'josh hutcherson', 'liam hemsworth'], ['jim parsons', 'rihanna', 'steve martin'], ['tom cruise', 'dakota fanning', 'miranda otto'], ['martin lawrence', 'will smith', 'jordi mollà'], ['antonio banderas', 'salma hayek', 'zach galifianakis'], ['angelina jolie', 'liev schreiber', 'chiwetel ejiofor'], ['russell crowe', 'jennifer connelly', 'emma watson'], ['jamie bell', 'andy serkis', 'daniel craig'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['nicole kidman', 'hugh jackman', 'essie davis'], ['jaden smith', 'will smith', 'sophie okonedo'], ['d. b. sweeney', 'alfre woodard', 'ossie davis'], ['ben stiller', 'rami malek', 'rebel wilson'], ['will ferrell', 'brad pitt', 'tina fey'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['jeff bridges', 'ryan reynolds', 'kevin bacon'], ['johnny depp', 'geoffrey rush', 'orlando bloom'], ['jennifer lawrence', 'josh hutcherson', 'liam hemsworth'], ['tom hanks', 'audrey tautou', 'ian mckellen'], ['jesse eisenberg', 'anne hathaway', 'leslie mann'], ['patrick stewart', 'hugh jackman', 'ian mckellen'], ['vin diesel', 'paul walker', 'jordana brewster'], ['robert downey jr.', 'jude law', 'jared harris'], ['sam worthington', 'liam neeson', 'ralph fiennes'], ['arnold schwarzenegger', 'sharon stone', 'rachel ticotin'], ['antonio banderas', 'vladimir kulich', 'dennis storhøi'], ['jeremy renner', 'rachel weisz', 'edward norton'], ['george clooney', "chris o'donnell", 'arnold schwarzenegger'], ['jim carrey', 'taylor momsen', 'jeffrey tambor'], ['dennis quaid', 'jake gyllenhaal', 'emmy rossum'], ['tom cruise', 'dougray scott', 'thandie newton'], ['george clooney', 'mark wahlberg', 'diane lane'], ['ioan gruffudd', 'jessica alba', 'chris evans'], ['suraj sharma', 'irrfan khan', 'ayush tandon'], ['nicolas cage', 'eva mendes', 'wes bentley'], ['matt damon', 'alicia vikander', 'tommy lee jones'], ['cameron diaz', 'drew barrymore', 'lucy liu'], ['noomi rapace', 'michael fassbender', 'guy pearce'], ['michael j. fox', 'geena davis', 'hugh laurie'], ['matt damon', 'jodie foster', 'sharlto copley'], ['vin diesel', 'thandie newton', 'karl urban'], ['joel kinnaman', 'gary oldman', 'michael keaton'], ['emile hirsch', 'christina ricci', 'matthew fox'], ['reese witherspoon', 'paul rudd', 'owen wilson'], ['tom cruise', 'cameron diaz', 'peter sarsgaard'], ['tom cruise', 'morgan freeman', 'olga kurylenko'], ['ewan mcgregor', 'natalie portman', 'hayden christensen'], ['ewan mcgregor', 'natalie portman', 'hayden christensen'], ['john goodman', 'billy crystal', 'mary gibbs'], ['hugh jackman', 'hiroyuki sanada', 'famke janssen'], ['liam neeson', 'ewan mcgregor', 'natalie portman'], ['nicolas cage', 'emma stone', 'ryan reynolds'], ['clovis cornillac', 'gérard depardieu', 'franck dubosc'], ['nicolas cage', 'adam beach', 'peter stormare'], ['chris hemsworth', 'charlize theron', 'emily blunt'], ['megan fox', 'will arnett', 'william fichtner'], ['sandra bullock', 'george clooney', 'ed harris'], ['pierce brosnan', 'linda hamilton', 'jamie renée smith'], ['megan fox', 'stephen amell', 'will arnett'], ['miles teller', 'kate mara', 'michael b. jordan'], ['ben stiller', 'jake cherry', 'carla gugino'], ['dwayne johnson', 'alexandra daddario', 'carla gugino'], ['pierce brosnan', 'jonathan pryce', 'michelle yeoh'], ['mel gibson', 'heath ledger', 'joely richardson'], ['george clooney', 'brad pitt', 'catherine zeta-jones'], ['angelina jolie', 'brad pitt', 'vince vaughn'], ['shailene woodley', 'theo james', 'kate winslet'], ['leonardo dicaprio', 'cate blanchett', 'kate beckinsale'], ['jack black', 'amanda peet', 'emily blunt'], ['seth rogen', 'jay chou', 'christoph waltz'], ['sullivan stapleton', 'eva green', 'lena headey'], ['hank azaria', 'neil patrick harris', 'jayma mays'], ['roseanne barr', 'judi dench', 'jennifer tilly'], ['shailene woodley', 'theo james', 'zoë kravitz'], ['hugh jackman', 'dakota goyo', 'evangeline lilly'], ['hank azaria', 'neil patrick harris', 'brendan gleeson'], ['sandra bullock', 'jason patric', 'willem dafoe'], ['asa butterfield', 'harrison ford', 'hailee steinfeld'], ['bruce willis', 'justin long', 'timothy olyphant'], ['elijah wood', 'ian mckellen', 'cate blanchett'], ['jackie chan', 'steve coogan', 'cécile de france'], ['will smith', 'jamie foxx', 'jon voight'], ['mike myers', 'dakota fanning', 'spencer breslin'], ['will smith', 'bridget moynahan', 'alan tudyk'], ['orlando bloom', 'eva green', 'jeremy irons'], ['michael j. fox', 'geena davis', 'hugh laurie'], ['anika noni rose', 'bruno campos', 'keith david'], ['matt damon', 'jessica chastain', 'kristen wiig'], ['ewan mcgregor', 'scarlett johansson', 'djimon hounsou'], ['warren beatty', 'diane keaton', 'goldie hawn'], ['nicolas cage', 'angelina jolie', 'giovanni ribisi'], ['russell crowe', 'joaquin phoenix', 'connie nielsen'], ['tom cruise', 'colin farrell', 'samantha morton'], ['daniel radcliffe', 'rupert grint', 'emma watson'], ['daniel craig', 'eva green', 'mads mikkelsen'], ['mark wahlberg', 'tim roth', 'helena bonham carter'], ['arnold schwarzenegger', 'linda hamilton', 'robert patrick'], ['christian bale', 'johnny depp', 'giovanni ribisi'], ['denzel washington', 'russell crowe', 'chiwetel ejiofor'], ['arnold schwarzenegger', 'jamie lee curtis', 'tom arnold'], ['denzel washington', 'john travolta', 'luis guzmán'], ['robert de niro', 'ben stiller', 'owen wilson'], ['will ferrell', 'mark wahlberg', 'eva mendes'], ['arnold schwarzenegger', 'james caan', 'vanessa williams'], ['jamie foxx', 'christoph waltz', 'leonardo dicaprio'], ['tom hulce', 'demi moore', 'tony jay'], ['david spade', 'john goodman', 'eartha kitt'], ['sylvester stallone', 'jason statham', 'dolph lundgren'], ['nicolas cage', 'diane kruger', 'justin bartha'], ['ed speleers', 'jeremy irons', 'sienna guillory'], ['max records', 'catherine keener', 'lauren ambrose'], ['josh hutcherson', 'amanda seyfried', 'colin farrell'], ['johnny depp', 'angelina jolie', 'paul bettany'], ['arnold schwarzenegger', 'gabriel byrne', 'kevin pollak'], ['leonardo dicaprio', 'djimon hounsou', 'jennifer connelly'], ['leonardo dicaprio', 'jonah hill', 'margot robbie'], ['val kilmer', 'tommy lee jones', 'jim carrey'], ['casper van dien', 'dina meyer', 'denise richards'], ['tom hanks', 'halle berry', 'jim broadbent'], ['emily barclay', 'abbie cornish', 'essie davis'], ['halle berry', 'benjamin bratt', 'sharon stone'], ['dwayne johnson', 'ian mcshane', 'john hurt'], ['joseph gordon-levitt', 'brian murray', 'david hyde pierce'], ['will ferrell', 'anna friel', 'danny mcbride'], ['sylvester stallone', 'jason statham', 'harrison ford'], ['edgar ramírez', 'luke bracey', 'teresa palmer'], ['jamie kennedy', 'alan cumming', 'traylor howard'], ['chris hemsworth', 'benjamin walker', 'cillian murphy'], ['eddie murphy', 'randy quaid', 'rosario dawson'], ['matt damon', 'greg kinnear', 'brendan gleeson'], ['noah schnapp', 'bill melendez', 'venus schultheis'], ['steve martin', 'campbell scott', 'ben gazzara'], ['brendan fraser', 'rachel weisz', 'john hannah'], ['leonardo dicaprio', 'daniel day-lewis', 'cameron diaz'], ['christian bale', 'ni ni', 'tong dawei'], ['shia labeouf', 'jeff bridges', 'zooey deschanel'], ['nicole kidman', 'matthew broderick', 'bette midler'], ['josh hartnett', 'ewan mcgregor', 'jason isaacs'], ['will ferrell', 'zach galifianakis', 'dylan mcdermott'], ['bruce willis', 'gary oldman', 'ian holm'], ['sarah jessica parker', 'kristin davis', 'cynthia nixon'], ['kenneth branagh', 'kevin kline', 'rosie perez'], ['john leguizamo', 'ray romano', 'chris wedge'], ['lily james', 'cate blanchett', 'richard madden'], ['rachel weisz', 'mark wahlberg', 'susan sarandon'], ['albert brooks', 'ellen degeneres', 'alexander gould'], ['elijah wood', 'ian mckellen', 'viggo mortensen'], ['elijah wood', 'ian mckellen', 'viggo mortensen'], ['jeff bridges', 'julianne moore', 'ben barnes'], ['angelina jolie', 'jon voight', 'iain glen'], ['johnny depp', 'paul bettany', 'rebecca hall'], ['sam neill', 'william h. macy', 'téa leoni'], ['james franco', 'freida pinto', 'john lithgow'], ['freddie highmore', 'mary-louise parker', 'nick nolte'], ['bruce willis', 'jai courtney', 'sebastian koch'], ['dennis quaid', 'billy bob thornton', 'jason patric'], ['craig t. nelson', 'holly hunter', 'samuel l. jackson'], ['geena davis', 'matthew modine', 'frank langella'], ['logan lerman', 'brandon t. jackson', 'alexandra daddario'], ['tommy lee jones', 'will smith', 'linda fiorentino'], ['tom hanks', 'tim allen', 'joan cusack'], ['denzel washington', 'chris pine', 'rosario dawson'], ['chris tucker', 'jackie chan', 'zhang ziyi'], ['harrison ford', 'michelle pfeiffer', 'diana scarwid'], ['bill hader', 'anna faris', 'james caan'], ['ray romano', 'john leguizamo', 'denis leary'], ['ben stiller', 'kristen wiig', 'patton oswalt'], ['cameron diaz', 'lucy liu', 'drew barrymore'], ['leonardo dicaprio', 'matt damon', 'jack nicholson'], ['eddie murphy', 'jackie chan', 'ming-na wen'], ['ben stiller', 'jack black', 'robert downey jr.'], ['daniel craig', 'rooney mara', 'christopher plummer'], ['bruce willis', 'jeremy irons', 'samuel l. jackson'], ['robert downey jr.', 'jude law', 'rachel mcadams'], ['jack huston', 'toby kebbell', 'rodrigo santoro'], ['michael j. fox', 'corey burton', 'claudia christian'], ['jason lee', 'justin long', 'bella thorne'], ['tom cruise', 'carice van houten', 'kenneth branagh'], ['adam sandler', 'john turturro', 'emmanuelle chriqui'], ['adam sandler', 'michelle monaghan', 'peter dinklage'], ['haley joel osment', "frances o'connor", 'sam robards'], ['eddie murphy', 'terence stamp', 'nathaniel parker'], ['jodie foster', 'matthew mcconaughey', 'james woods'], ['kevin bacon', 'elisabeth shue', 'josh brolin'], ['nicole kidman', 'sean penn', 'catherine keener'], ['logan lerman', 'alexandra daddario', 'douglas smith'], ['angelina jolie', 'gerard butler', 'noah taylor'], ['jesse eisenberg', 'woody harrelson', 'mark ruffalo'], ['val kilmer', 'elisabeth shue', 'rade serbedzija'], ['robert redford', 'brad pitt', 'catherine mccormack'], ['gary sinise', 'tim robbins', 'don cheadle'], ['jesse eisenberg', 'anne hathaway', 'leslie mann'], ['robin williams', 'sam neill', 'embeth davidtz'], ['tommy lee jones', 'anne heche', 'gaby hoffmann'], ['harrison ford', 'brad pitt', 'margaret colin'], ['harrison ford', 'liam neeson', 'peter sarsgaard'], ['arnold schwarzenegger', 'james earl jones', 'max von

In [205]:
#final recommendation function for both movie name and actor name
def recommend(movie_name):
    sim = []
    recs=[]
    flag=0
    movie_name=movie_name.lower()
    
    #checking if movie name is present
    if movie_name in mov:
        flag=1
        
        movie_index=final[final['lower_title']== movie_name].index[0]
        
    #case when actor name is entered, checking if its present
    else:
        actor_name=movie_name.lower()
        for i in range(len(listt_cast)):
            if actor_name in listt_cast[i]:
                
                flag=2
                
                title= final.iloc[i]['lower_title']
                break
        if flag==2:
            movie_index=final[final['lower_title']== title].index[0]
        
        
    if flag==1 or flag==2:
        
        #finding movies similar to given movie
        L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])
        #print(type(L))
        l = np.array(L)
        
        
        #recommending top 5 most similar movies
        for i in L[1:6]:
            print(final.iloc[i[0]]['original_title'])
            recs.append(final.iloc[i[0]]['original_title'])
        
        for i in range(1, 6):
            sim.append(l[i,1])
            
        print(sim)
        
        # Average of cosine similarities
        print(np.mean(sim))
        return recs
    
    #if movie/actor name not present in dataset
    else:
        return recs

## Accuracy Method 1:

In [198]:
rec = recommend('Frozen')

Aladdin
Spirit: Stallion of the Cimarron
The Book of Life
Delgo
Curious George
[0.33477148537926144, 0.3198440903483299, 0.2946187459145688, 0.2923217018990037, 0.27823802660725183]
0.30395881002968317

In [190]:
rec =recommend('Harry Potter and the Chamber of Secrets')

Harry Potter and the Prisoner of Azkaban
Harry Potter and the Order of the Phoenix
Harry Potter and the Goblet of Fire
Harry Potter and the Philosopher's Stone
Harry Potter and the Half-Blood Prince
[0.5131580057907854, 0.4666282626286915, 0.41550015922716765, 0.3840122885898554, 0.3696246621802185]
0.42978467568334366

In [191]:
rec=recommend('Iron Man')

Iron Man 2
Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
The Avengers
[0.4540034830713325, 0.42884501393511804, 0.3649324991288249, 0.2738612787525831, 0.2672612419124244]
0.3577807033600566

In [192]:
rec=recommend('Batman')

Batman & Robin
Batman Begins
The Dark Knight Rises
Batman Returns
The Dark Knight
[0.4191700136497969, 0.2932942300427066, 0.29221395296494723, 0.29221395296494723, 0.2714229994642801]
0.3136630298173356

In [195]:
rec=recommend('The Martian')

Red Planet
Escape from Planet Earth
Mission to Mars
Meet Dave
Armageddon
[0.28284271247461906, 0.2626128657194451, 0.2598076211353316, 0.25584085962673253, 0.2455762454059682]
0.2613360608724193

## Accuracy Method 2:

In [109]:
input_actors = ['daniel craig','chris evans','will smith','johnny depp','meryl streep','scarlett johansson','emma watson','emma stone','jennifer lawrence','zac efron']
expected_movies = ['Skyfall','Captain America: Civil War','Men in Black','Pirates of the Caribbean: The Curse of the Black Pearl','The Devil Wears Prada','Avengers: Age of Ultron','Harry Potter and the Chamber of Secrets','The Amazing Spider-Man 2','X-Men','Baywatch']
accuracy = []
all_predictions = []
for i in range(len(input_actors)):
    predictions = recommend(input_actors[i])
    all_predictions.append(predictions)
    accuracy.append(expected_movies[i] in predictions)

Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love
Thunderball
Avengers: Age of Ultron
Captain America: Civil War
Iron Man 3
Iron Man
Captain America: The First Avenger
Timecop
Men in Black
Project Almanac
The Helix... Loaded
Men in Black II
Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
20,000 Leagues Under the Sea
Puss in Boots
Can't Hardly Wait
Someone Like You...
To Save A Life
The Incredibly True Adventure of Two Girls In Love
Bride & Prejudice
Captain America: The Winter Soldier
Captain America: The First Avenger
Iron Man 3
Avengers: Age of Ultron
Iron Man 2
Harry Potter and the Order of the Phoenix
Harry Potter and the Goblet of Fire
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Chamber of Secrets
Harry Potter and the Philosopher's Stone
The Amazing Spider-Man 2
Spider-Man 3
Spider-Man
Hook
Spider-Man 2
X-Men: First Class
X-Men: Days of Future Past
X-Men
X-Men: The Last Stand
X2
The Young Unknowns
Good Luck Chuck
Rain Man
Charlie Bartlett
Urbania

In [112]:
d = {'Actor inputted by user':input_actors,'Movies Predicted' : all_predictions, 'Expected Movie': expected_movies}

In [113]:
pred_df = pd.DataFrame(d)
pred_df

,Actor inputted by user,Movies Predicted,Expected Movie
0,daniel craig,"[Quantum of Solace, Never Say Never Again, Sky...",Skyfall
1,chris evans,"[Avengers: Age of Ultron, Captain America: Civ...",Captain America: Civil War
2,will smith,"[Timecop, Men in Black, Project Almanac, The H...",Men in Black
3,johnny depp,"[Pirates of the Caribbean: Dead Man's Chest, P...",Pirates of the Caribbean: The Curse of the Bla...
4,meryl streep,"[Can't Hardly Wait, Someone Like You..., To Sa...",The Devil Wears Prada
5,scarlett johansson,"[Captain America: The Winter Soldier, Captain ...",Avengers: Age of Ultron
6,emma watson,"[Harry Potter and the Order of the Phoenix, Ha...",Harry Potter and the Chamber of Secrets
7,emma stone,"[The Amazing Spider-Man 2, Spider-Man 3, Spide...",The Amazing Spider-Man 2
8,jennifer lawrence,"[X-Men: First Class, X-Men: Days of Future Pas...",X-Men
9,zac efron,"[The Young Unknowns, Good Luck Chuck, Rain Man...",Baywatch

In [106]:
#Determine the accuracy of the above predefined sample by counting the number of 
#matches of the expected word in the found predictions

c = 0
for i in accuracy:
    if i == True:
        c += 1
acc = c/len(accuracy)
print("Accuracy:", acc)

Accuracy: 0.8